version: '3.8'
services:
  database:
    container_name: project-postgresql
    image: postgres
    restart: always
    volumes:
      - ./prisma:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - '5452:5432'